HiQo.StaffManagement.WEB/Areas/Admin/Controllers/UserController.cs
using System;
using System.Web.Mvc;
using AutoMapper;
using HiQo.StaffManagement.Core.Models;
using HiQo.StaffManagement.Domain.EntitiesDto;
using HiQo.StaffManagement.Domain.Services.Interface;

namespace HiQo.StaffManagement.WEB.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _service;
        private readonly IUpsertUserService _upsertUserService;

        public UserController(IUserService service, IUpsertUserService upsertUserService)
        {
            _service = service ?? throw new ArgumentNullException();
            _upsertUserService = upsertUserService ?? throw new ArgumentNullException();
        }

        public ActionResult Index()
        {
            return View(_service.GetAll());
        }

        public ActionResult UpdateUser(int userId)
        {
            var info = _upsertUserService.GetSharedInfoDto();
            var departmentList = new SelectList(info.DepartmentDtos, "DepartmentDtoId", "Name");
            var categoryList = new SelectList(info.CategoryDtos, "CategoryDtoId", "Name");
            var positionList = new SelectList(info.PositionDtos, "PositionDtoId", "Name");
            var positionLevelList = new SelectList(info.PositionLevelDtos, "PositionLevelDtoId", "Name");
            var roleList = new SelectList(info.RoleDtos, "RoleDtoId", "Name");
            ViewBag.Departments = departmentList;
            ViewBag.Category = categoryList;
            ViewBag.Position = positionList;
            ViewBag.PositionLevel = positionLevelList;
            ViewBag.Role = roleList;
            var user = Mapper.Map<UserDto, UpsertUser>(_service.GetById(userId));
            return View("UpsertUser", user);
        }

        public ActionResult CreateUser(int id)
        {
            var info = _upsertUserService.GetSharedInfoDto();
            var departmentList = new SelectList(info.DepartmentDtos, "DepartmentDtoId", "Name");
            var categoryList = new SelectList(info.CategoryDtos, "CategoryDtoId", "Name");
            var positionList = new SelectList(info.PositionDtos, "PositionDtoId", "Name");
            var positionLevelList = new SelectList(info.PositionLevelDtos, "PositionLevelDtoId", "Name");
            var roleList = new SelectList(info.RoleDtos, "RoleDtoId", "Name");
            ViewBag.Departments = departmentList;
            ViewBag.Category = categoryList;
            ViewBag.Position = positionList;
            ViewBag.PositionLevel = positionLevelList;
            ViewBag.Role = roleList;
            return View("UpsertUser", null);
        }

        [HttpPost]
        public ActionResult EditUser(UpsertUser upsertUser)
        {
            var user = Mapper.Map<UserDto>(upsertUser);
            if (user.UserDtoId == 0)
                _service.Create(user);
            else
                _service.Update(user);
            return View();
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/CategoryController.cs
using System;
using System.Web.Mvc;
using HiQo.StaffManagement.Domain.Services.Interface;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service ?? throw new ArgumentNullException();
        }

        public ActionResult Index()
        {
            return View(_service.GetAll());
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/DepartmentController.cs
using System;
using System.Web.Mvc;
using HiQo.StaffManagement.Domain.Services.Interface;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _service;

        public DepartmentController(IDepartmentService service)
        {
            _service = service ?? throw new ArgumentNullException();
        }

        public ActionResult Index()
        {
            return View(_service.GetAll());
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/ErrorController.cs
using System.Web;
using System.Web.Mvc;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult HttpError404(string message)
        {
            ViewBag.Error = message;
            return View("HttpError404");
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/PositionController.cs
using System;
using System.Web.Mvc;
using HiQo.StaffManagement.Domain.Services.Interface;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class PositionController : Controller
    {
        private readonly IPositionService _service;

        public PositionController(IPositionService service)
        {
            _service = service ?? throw new ArgumentNullException();
        }

        public ActionResult Index()
        {
            return View(_service.GetAll());
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/PositionLevelController.cs
using System;
using System.Web.Mvc;
using HiQo.StaffManagement.Domain.Services.Interface;


namespace HiQo.StaffManagement.WEB.Controllers
{
    public class PositionLevelController : Controller
    {
        private readonly IPositionLevelService _service;

        public PositionLevelController(IPositionLevelService service)
        {
            _service = service ?? throw new ArgumentNullException();
        }

        public ActionResult Index()
        {
            return View(_service.GetAll());
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/UserController.cs
using System;
using System.Web;
using System.Web.Mvc;
using HiQo.StaffManagement.Domain.Services.Interface;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _service;
        private readonly IUpsertUserService _upsertUserService;

        public UserController(IUserService service, IUpsertUserService upsertUserService)
        {
            _service = service ?? throw new ArgumentNullException();
            _upsertUserService = upsertUserService ?? throw new ArgumentNullException();
        }

        public ActionResult Index()
        {
            return View(_service.GetAll());
        }

        public ActionResult GetUserProfile(int userId)
        {
            return View("UserProfile", _service.GetById(userId));
        }
    }
}

HiQo.StaffManagement.WEB/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Users", "Index", "User", new { area = "Admin" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Create new user", "CreateUser", "User", new { area = "Admin", id = 0 }, new { @class = "navbar-brand" })
                @Html.ActionLink("Default area", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HiQo.StaffManagement.WEB/Areas/Admin/Views/User/EditUser.cshtml
@{
    ViewBag.Title = "EditUser";
}

<h2>EditUser</h2>

HiQo.StaffManagement.WEB/Areas/Admin/Views/User/Index.cshtml
@model IEnumerable<HiQo.StaffManagement.Domain.EntitiesDto.UserDto>
@{
    ViewBag.Title = "Index";
}
<html>
<head>
    <title>@ViewBag.Title </title>
</head>
<body>
<h2>User</h2>
<table class="table">
    <thead class="alert-danger">
    <tr>
        <td>First Name</td>
        <td>Second Name</td>
        <td>Position</td>
        <td>Position level</td>
        <td></td>
    </tr>
    </thead>
    <tbody class="tab-content">
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.FirstName</td>
            <td>@user.LastName</td>
            <td>@user.Position.Name</td>
            <td>@user.PositionLevel.Name</td>
            <td>
                @using (Html.BeginForm("UpdateUser", "User", new { area = "Admin", userId = user.UserDtoId }))
                {
                    <button type="submit" class="btn btn-default">Update Profile</button>
                }

            </td>
        </tr>
    }
    </tbody>

</table>
</body>
</html>

HiQo.StaffManagement.WEB/Areas/Admin/Views/User/UpsertUser.cshtml
@model  HiQo.StaffManagement.Core.Models.UpsertUser
@{
    ViewBag.Title = "UpdateUser";
}

<html>
<head>
    <title>@ViewBag.Title </title>
</head>
<body>
    <div class=" panel panel-default" style="width: 400px">
        <div class="panel-heading alert-danger h4">
            @if (Model == null)
            {
                <text>Create new user</text>
            }
            else
            {
                <text>Update user</text>
            }
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @using (Html.BeginForm("EditUser", "User", new { area = "Admin" }, FormMethod.Post))
                        {
                            @Html.HiddenFor(user => user.UpsertUserId);
                            @Html.LabelFor(user => user.FirstName, "First name:")
                            <p>@Html.EditorFor(user => user.FirstName, new { htmlAttributes = new { @class = "form-control" } }) </p>
                            @Html.LabelFor(user => user.LastName, "Last name:")
                            <p>@Html.EditorFor(user => user.LastName, new { htmlAttributes = new { @class = "form-control" } })</p>
                            @Html.LabelFor(user => user.DateOfBirth, "Date of birth")
                            <p>@Html.EditorFor(user => user.DateOfBirth, new { htmlAttributes = new { @class = "form-control", @type = "date" } })</p>
                            <p>@Html.LabelFor(user => user.DepartmentId, "Department:")</p>
                            <p>@Html.DropDownListFor(user => user.DepartmentId, ViewBag.Departments as SelectList, new { @class = "form-control" })</p>
                            <p>@Html.LabelFor(user => user.CategoryId, "Category:")</p>
                            <p>@Html.DropDownListFor(user => user.CategoryId, ViewBag.Category as SelectList, new { @class = "form-control" })</p>
                            <p>@Html.LabelFor(user => user.PositionId, "Position:")</p>
                            <p>@Html.DropDownListFor(user => user.PositionId, ViewBag.Position as SelectList, new { @class = "form-control" })</p>
                            <p>@Html.LabelFor(user => user.PositionLevelId, "Position level:")</p>
                            <p>@Html.DropDownListFor(user => user.PositionLevelId, ViewBag.PositionLevel as SelectList, new { @class = "form-control" })</p>
                            if (Model == null)
                            {
                                <p>@Html.LabelFor(user => user.RoleId, "Role:")</p>
                                <p>@Html.DropDownListFor(user => user.RoleId, ViewBag.Role as SelectList, new { @class = "form-control" })</p>
                            }
                            else
                            {
                                @Html.HiddenFor(user => user.RoleId);                                
                            }
                            <br/>
                            <input type="submit" value="Save changes" , class="btn btn-default" />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

HiQo.StaffManagement.WEB/Views/Category/Index.cshtml
@model IEnumerable<HiQo.StaffManagement.Domain.EntitiesDto.CategoryDto>
@{
  ViewBag.Title = "Index";
}
<html>
<head>
    <title>Categories</title>
</head>
<body>
    <h2>Categoties</h2>
    <table class="table">
        <thead>
            <tr>
                <td>Name</td>
                <td>Department</td>
            </tr>
        </thead>
        <tbody class="tab-content">
            @foreach (var category in Model)
            {
                <tr>
                    <td>@category.Name</td>
                    <td>@category.Department.Name</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

HiQo.StaffManagement.WEB/Views/Department/Index.cshtml
@model IEnumerable<HiQo.StaffManagement.Domain.EntitiesDto.DepartmentDto>
@{
    ViewBag.Title = "Index";
}
<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
    <h2>Department</h2>
    <table class="table">
        <thead>
            <tr>
                <td>Name</td>
            </tr>
        </thead>
        <tbody class=" body-content">
            @foreach (var department in Model)
            {
                <tr>
                    <td>@department.Name</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

HiQo.StaffManagement.WEB/Views/Position/Index.cshtml
@model IEnumerable<HiQo.StaffManagement.Domain.EntitiesDto.PositionDto>
@{
    ViewBag.Title = "Index";
}
<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
<h2>Positions</h2>
<table class="table">
    <thead class ="alert-danger">
    <tr>
        <td>Name</td>
        <td>Category</td>
        <td>Department</td>
    </tr>
    </thead>
    <tbody class="tab-content">
    @foreach (var position in Model)
    {
        <tr>
            <td>@position.Name</td>
            <td>@position.Category.Name</td>
            <td>@position.Category.Department.Name</td>
        </tr>
    }
    </tbody>
</table>
</body>
</html>

HiQo.StaffManagement.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Users", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Positions", "Index", "Position", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Categories", "Index", "Category", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Departments", "Index", "Department", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Positions Levels", "Index", "PositionLevel", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Admin Area", "Index", "User", new {area="Admin"}, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/datetime")
@RenderSection("scripts", required: false)
</body>
</html>

HiQo.StaffManagement.WEB/Views/User/Index.cshtml
@model IEnumerable<HiQo.StaffManagement.Domain.EntitiesDto.UserDto>
@{
    ViewBag.Title = "Index";
}
<html>
<head>
    <title>@ViewBag.Title </title>
</head>
<body>
    <h2>User</h2>
    <table class="table">
        <thead class="alert-danger">
            @*А есть "thead-dark" вот он не работает,
                причем инфа про него из доументации*@
            <tr>
                <td>First Name</td>
                <td>Second Name</td>
                <td>Position</td>
                <td>Position level</td>
                <td></td>
            </tr>
        </thead>
        <tbody class="tab-content">
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.FirstName</td>
                    <td>@user.LastName</td>
                    <td>@user.Position.Name</td>
                    <td>@user.PositionLevel.Name</td>
                    <td>
                        @*<button type="submit" class="btn-default btn-sm">@Html.ActionLink("Users", "GetUserProfile", "User", new { userid = user.UserDtoId},null)</button>*@
                        @using (Html.BeginForm("GetUserProfile", "User", new { userId = user.UserDtoId }))
                        {
                            <button type="submit" class="btn btn-default">@user.FirstName Profile</button>
                        }

                    </td>
                </tr>
            }
        </tbody>

    </table>
</body>
</html>

HiQo.StaffManagement.WEB/Views/User/UserProfile.cshtml
@model HiQo.StaffManagement.Domain.EntitiesDto.UserDto
@{
    ViewBag.Title = "UserProfile";
}
<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
<div class=" panel panel-default" style="width: 400px">
    <div class="panel-heading alert-danger h4">@Model.FirstName @Model.LastName</div>
    <div class="panel-body">
        <p><b>Date of Birth: </b>@Model.DateBirth.ToShortDateString()</p>
        <p><b>Department:</b> @Model.Department.Name</p>
        <p><b>Category:</b> @Model.Category.Name</p>
        <p><b>Position:</b> @Model.Position.Name</p>
        <p><b>Position level:</b> @Model.PositionLevel.Name</p>
        <p>
            <b>Level:</b>
            @if (Model.PositionLevel.Level == null)
            {
                <span>-</span>
            }
            else
            {
                <span>@Model.PositionLevel.Level</span>
            }
        </p>
    </div>
    <div class="panel-footer">
        @using (Html.BeginForm("Index", "User", new {area = ""})) 
        { 
            <button type="submit" class="btn btn-default">Get Back</button> 
        }
    </div>
</div>
</body>
</html>